{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Dynamo for Revit Python Scripting \n",
    "\n",
    "\n",
    "#### 4. Revit API"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.1 Collecting Elements"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "watch this video"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.2 Creating a collector"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "family = UnwrapElement(IN[0])\n",
    "\n",
    "#Filtered Element Collector\n",
    "collector = FilteredElementCollector(doc, doc.ActiveView.Id)\n",
    "\n",
    "#Quick Filter\n",
    "filter = ElementCategoryFilter(BuiltInCategory.OST_Doors)\n",
    "doors = collector.WherePasses(filter).ToElements()\n",
    "\n",
    "#Slow Filter\n",
    "instancefilter = FamilyInstanceFilter(doc, family.Id)\n",
    "doorinstance = collector.OfCategory(BuiltInCategory.OST_Doors).WherePasses(instancefilter).ToElementIds()\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = doorinstance"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.3 Getting Revit Parameters"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "doorCat = UnwrapElement(IN[0])\n",
    "output = []\n",
    "\n",
    "#Get the project document.\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "#Filter for doors.\n",
    "collector = FilteredElementCollector(doc, doc.ActiveView.Id)\n",
    "doors = collector.OfCategoryId(doorCat.Id).FirstElement()\n",
    "\n",
    "#Get Parameters\n",
    "parameters = doors.GetOrderedParameters()\n",
    "\n",
    "for parameter in parameters:\n",
    "\t#output.append(parameter.Definition.Name)\n",
    "\toutput.append(parameter.Definition.BuiltInParameter)\n",
    "\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.4 Setting Revit Parameters"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "doorCat = UnwrapElement(IN[0])\n",
    "output = []\n",
    "\n",
    "#Get the project document.\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "#Filter for doors.\n",
    "collector = FilteredElementCollector(doc, doc.ActiveView.Id)\n",
    "doors = collector.OfCategoryId(doorCat.Id).FirstElement()\n",
    "\n",
    "#Get Parameters\n",
    "parameters = doors.GetOrderedParameters()\n",
    "\n",
    "for parameter in parameters:\n",
    "\t#output.append(parameter.Definition.Name)\n",
    "\toutput.append(parameter.Definition.BuiltInParameter)\n",
    "\t\n",
    "doormat = doors.get_Parameter(BuiltInParameter.DOOR_FRAME_MATERIAL)\n",
    "\n",
    "parameterstoragetype = doormat.StorageType\n",
    "\n",
    "\n",
    "#Set Parameter\n",
    "TransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "doormat.Set(\"Wood\")\n",
    "\n",
    "TransactionManager.Instance.TransactionTaskDone()\n",
    "\n",
    "paramvalue = doormat.AsString()\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = paramvalue"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.5 Creating Line Driven Elements"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "Designscript below"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "t1 = [0, 0, 13000, 13000, 20000, 20000];\n",
    "t2 = [0, 12000, 10000, 13000, 13000, 0];\n",
    "point1 = Point.ByCoordinates(t1, t2, 0);\n",
    "polygon1 = Polygon.ByPoints(point1);"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "clr.ImportExtensions(Revit.GeometryConversion)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "output = []\n",
    "lines = IN[0].ToRevitType()\n",
    "\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "#Create Curve Array\n",
    "carray = CurveArray()\n",
    "\t\t\n",
    "#Loop through lines\n",
    "for line in lines:\n",
    "\tcarray.Append(line)\n",
    "\t\t\n",
    "#Start Transaction\n",
    "TransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "#Create Floor\n",
    "floor = doc.Create.NewFloor(carray, False)\n",
    "output.append(floor.ToDSType(False))\n",
    "\n",
    "#Get Floor Parameters\n",
    "level = floor.LookupParameter(\"Level\").AsElementId()\n",
    "\n",
    "#Create Walls\n",
    "for line in lines:\n",
    "\twall = Wall.Create(doc, line, level, False)\n",
    "\toutput.append(wall.ToDSType(False))\n",
    "\n",
    "#End Transaction\n",
    "TransactionManager.Instance.TransactionTaskDone()\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.6 Element Locations"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "clr.ImportExtensions(Revit.GeometryConversion)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#Import Math Module\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "couch = UnwrapElement(IN[0])\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "#Collect Rooms\n",
    "filter = Architecture.RoomFilter()\n",
    "rooms = FilteredElementCollector(doc).WherePasses(filter).ToElements()\n",
    "\n",
    "#Find Office 2\n",
    "office = None\n",
    "for room in rooms:\n",
    "\tif room.LookupParameter(\"Name\").AsString() == \"Office 2\":\n",
    "\t\toffice = room\n",
    "\n",
    "TransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "#Setting Locations\n",
    "couch.Location.Point = office.Location.Point\n",
    "\n",
    "\n",
    "TransactionManager.Instance.TransactionTaskDone()\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = office"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.7 "
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "clr.ImportExtensions(Revit.GeometryConversion)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#Import Math Module\n",
    "from math import radians\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "couch = UnwrapElement(IN[0])\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "#Collect Rooms\n",
    "filter = Architecture.RoomFilter()\n",
    "rooms = FilteredElementCollector(doc).WherePasses(filter).ToElements()\n",
    "\n",
    "#Find Office 2\n",
    "office = None\n",
    "for room in rooms:\n",
    "\tif room.LookupParameter(\"Name\").AsString() == \"Office 2\":\n",
    "\t\toffice = room\n",
    "\n",
    "TransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "#Setting Locations\n",
    "#couch.Location.Point = office.Location.Point\n",
    "\n",
    "#Copy Element\n",
    "movevector = XYZ(0,5,0)\n",
    "#copyelement = ElementTransformUtils.CopyElement(doc, couch.Id, movevector)\n",
    "\n",
    "#Rotate Element\n",
    "point = couch.Location.Point\n",
    "endpoint = XYZ(point.X, point.Y, point.Z + 10)\n",
    "axis = Line.CreateBound(point, endpoint)\n",
    "\n",
    "ElementTransformUtils.RotateElement(doc, couch.Id, axis, radians(180))\n",
    "\n",
    "\n",
    "TransactionManager.Instance.TransactionTaskDone()\n",
    "\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = couch"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.8 Adjusting Elements"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "plan = UnwrapElement(IN[0])\n",
    "toggle = IN[1]\n",
    "\n",
    "output = []\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "if toggle:\n",
    "\n",
    "\tfilter = Architecture.RoomFilter()\n",
    "\tcollector = FilteredElementCollector(doc, plan.Id).WherePasses(filter).ToElements()\n",
    "\t\n",
    "\tTransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "\tfor room in collector:\n",
    "\t\n",
    "\t\t#Get View Family Type of Plan\n",
    "\t\tviewtypeid = plan.GetTypeId()\n",
    "\t\tlevel = room.LevelId\n",
    "\n",
    "\t\t#Create View\n",
    "\t\troomview = ViewPlan.Create(doc, viewtypeid, level)\n",
    "\n",
    "\t\t#Get Room Bounding Box and Create New \n",
    "\n",
    "\n",
    "\t\t#Set the new Bounding Box\n",
    "\n",
    "\n",
    "\t\t#Name the New View\n",
    "\n",
    "\n",
    "\tTransactionManager.Instance.TransactionTaskDone()\n",
    "\t\n",
    "else:\n",
    "\t\n",
    "\toutput.append(\"Set to True\")\n",
    "\t\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.9 Creating a View"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "#Import Revit Nodes\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.Elements)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "import Autodesk\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "# Import DocumentManager and TransactionManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "plan = UnwrapElement(IN[0])\n",
    "toggle = IN[1]\n",
    "\n",
    "output = []\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "if toggle:\n",
    "\n",
    "\tfilter = Architecture.RoomFilter()\n",
    "\tcollector = FilteredElementCollector(doc, plan.Id).WherePasses(filter).ToElements()\n",
    "\t\n",
    "\tTransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\n",
    "\tfor room in collector:\n",
    "\t\n",
    "\t\t#Get View Family Type of Plan\n",
    "\t\tviewtypeid = plan.GetTypeId()\n",
    "\t\tlevel = room.LevelId\n",
    "\n",
    "\t\t#Create View\n",
    "\t\troomview = ViewPlan.Create(doc, viewtypeid, level)\n",
    "\n",
    "\t\t#Get Room Bounding Box and Create New \n",
    "\t\troombb = room.get_BoundingBox(plan)\n",
    "\t\trmax = roombb.Max\n",
    "\t\trmin = roombb.Min\n",
    "\t\tnewmax = XYZ(rmax.X + 1, rmax.Y + 1, rmax.Z)\n",
    "\t\tnewmin = XYZ(rmin.X - 1, rmin.Y - 1, rmin.Z)\n",
    "\t\tnewBB = BoundingBoxXYZ()\n",
    "\t\tnewBB.Max = newmax\n",
    "\t\tnewBB.Min = newmin\n",
    "\n",
    "\t\t#Set the new Bounding Box\n",
    "\t\troomview.CropBoxActive = True\n",
    "\t\troomview.CropBox = newBB\n",
    "\n",
    "\t\t#Name the New View\n",
    "\t\troomview.ViewName = room.LookupParameter(\"Name\").AsString()\n",
    "\t\toutput.append(roomview.ToDSType(True))\n",
    "\n",
    "\tTransactionManager.Instance.TransactionTaskDone()\n",
    "\t\n",
    "else:\n",
    "\t\n",
    "\toutput.append(\"Set to True\")\n",
    "\t\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.10 View Bounding Boxes"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "import clr\n",
    "\n",
    "# Import DocumentManager\n",
    "clr.AddReference(\"RevitServices\")\n",
    "import RevitServices\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "\n",
    "clr.AddReference(\"RevitNodes\")\n",
    "import Revit\n",
    "clr.ImportExtensions(Revit.GeometryConversion)\n",
    "\n",
    "# Import RevitAPI\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "from Autodesk.Revit.DB import *\n",
    "\n",
    "#Add List Object\n",
    "from System.Collections.Generic import List\n",
    "\n",
    "#The inputs to this node will be stored as a list in the IN variables.\n",
    "views = UnwrapElement(IN[0])\n",
    "output = []\n",
    "\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "for view in views:\n",
    "\n",
    "\t#Create Multi Category Filter\n",
    "\tcategories = List[BuiltInCategory]()\n",
    "\tcategories.Add(BuiltInCategory.OST_Doors)\n",
    "\tcategories.Add(BuiltInCategory.OST_Windows)\n",
    "\tcategories.Add(BuiltInCategory.OST_Furniture)\n",
    "\t\n",
    "\tfilter = ElementMulticategoryFilter(categories)\n",
    "\tcollector = FilteredElementCollector(doc, view.Id).WherePasses(filter).WhereElementIsNotElementType().ToElements()\n",
    "\n",
    "\t#Tag Element\n",
    "\tTransactionManager.Instance.EnsureInTransaction(doc)\n",
    "\t\n",
    "\ttry:\n",
    "\t\tfor element in collector:\n",
    "\t\t\ttags = IndependentTag.Create(doc,view.Id, Reference(element), False, TagMode.TM_ADDBY_CATEGORY, TagOrientation.Horizontal, element.Location.Point)\n",
    "\t\t\toutput.append(element)\n",
    "\texcept:\n",
    "\t\toutput.append(\"Element cannot be tagged\")\t\n",
    "\n",
    "\tTransactionManager.Instance.TransactionTaskDone()\n",
    "\t\n",
    "#Assign your output to the OUT variable.\n",
    "OUT = output"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4.11 Revit API and IronPython Types"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
